// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodTracker.Infrastructure.Data;


#nullable disable

namespace MoodTracker.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218203014_Note_Date_Is_Unique")]
    partial class Note_Date_Is_Unique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MoodTracker.Server.Domain.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Medications", (string)null);
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.Thought", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Thoughts", (string)null);
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.Medication", b =>
                {
                    b.HasOne("MoodTracker.Server.Domain.Note", null)
                        .WithMany("_medications")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MoodTracker.Server.Domain.Medication+Dosage", "Dose", b1 =>
                        {
                            b1.Property<int>("MedicationId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DoseUnit");

                            b1.Property<uint>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DoseValue");

                            b1.HasKey("MedicationId");

                            b1.ToTable("Medications");

                            b1.WithOwner()
                                .HasForeignKey("MedicationId");
                        });

                    b.Navigation("Dose")
                        .IsRequired();
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.Note", b =>
                {
                    b.OwnsOne("MoodTracker.Server.Domain.Mood", "Mood", b1 =>
                        {
                            b1.Property<int>("NoteId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Color")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MoodColor");

                            b1.Property<int>("Rate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MoodRate");

                            b1.HasKey("NoteId");

                            b1.ToTable("Notes");

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.Navigation("Mood");
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.Thought", b =>
                {
                    b.HasOne("MoodTracker.Server.Domain.Note", null)
                        .WithMany("_thoughts")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.Note", b =>
                {
                    b.Navigation("_medications");

                    b.Navigation("_thoughts");
                });
#pragma warning restore 612, 618
        }
    }
}
