// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodTracker.Infrastructure.Data;


#nullable disable

namespace MoodTracker.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MoodTracker.Server.Domain.MedicationSetAggregate.Med", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicationSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedicationSetId");

                    b.ToTable("Meds", "sets");
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.MedicationSetAggregate.MedicationSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MedicationSets", "sets");
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.NoteAggregate.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Medications", (string)null);
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.NoteAggregate.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.NoteAggregate.Thought", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Thoughts", (string)null);
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.MedicationSetAggregate.Med", b =>
                {
                    b.HasOne("MoodTracker.Server.Domain.MedicationSetAggregate.MedicationSet", null)
                        .WithMany("_medications")
                        .HasForeignKey("MedicationSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MoodTracker.Server.Domain.Dosage", "Dose", b1 =>
                        {
                            b1.Property<int>("MedId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DoseUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("DoseValue");

                            b1.HasKey("MedId");

                            b1.ToTable("Meds", "sets");

                            b1.WithOwner()
                                .HasForeignKey("MedId");
                        });

                    b.Navigation("Dose")
                        .IsRequired();
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.NoteAggregate.Medication", b =>
                {
                    b.HasOne("MoodTracker.Server.Domain.NoteAggregate.Note", null)
                        .WithMany("_medications")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MoodTracker.Server.Domain.Dosage", "Dose", b1 =>
                        {
                            b1.Property<int>("MedicationId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DoseUnit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("DoseValue");

                            b1.HasKey("MedicationId");

                            b1.ToTable("Medications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicationId");
                        });

                    b.Navigation("Dose")
                        .IsRequired();
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.NoteAggregate.Note", b =>
                {
                    b.OwnsOne("MoodTracker.Server.Domain.NoteAggregate.Mood", "Mood", b1 =>
                        {
                            b1.Property<int>("NoteId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Color")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MoodColor");

                            b1.Property<int>("Rate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MoodRate");

                            b1.HasKey("NoteId");

                            b1.ToTable("Notes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.Navigation("Mood");
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.NoteAggregate.Thought", b =>
                {
                    b.HasOne("MoodTracker.Server.Domain.NoteAggregate.Note", null)
                        .WithMany("_thoughts")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.MedicationSetAggregate.MedicationSet", b =>
                {
                    b.Navigation("_medications");
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.NoteAggregate.Note", b =>
                {
                    b.Navigation("_medications");

                    b.Navigation("_thoughts");
                });
#pragma warning restore 612, 618
        }
    }
}
