// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodTracker.Server.Infrasctructure;

#nullable disable

namespace MoodTracker.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MoodTracker.Server.Domain.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Days", (string)null);
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("Medications", (string)null);
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.Day", b =>
                {
                    b.OwnsOne("MoodTracker.Server.Domain.Mood", "Mood", b1 =>
                        {
                            b1.Property<int>("DayId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Rate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MoodRate");

                            b1.HasKey("DayId");

                            b1.ToTable("Days");

                            b1.WithOwner()
                                .HasForeignKey("DayId");
                        });

                    b.Navigation("Mood")
                        .IsRequired();
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.Medication", b =>
                {
                    b.HasOne("MoodTracker.Server.Domain.Day", null)
                        .WithMany("_medications")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("MoodTracker.Server.Domain.Medication+Dosage", "Dose", b1 =>
                        {
                            b1.Property<int>("MedicationId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DoseUnit");

                            b1.Property<uint>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DoseValue");

                            b1.HasKey("MedicationId");

                            b1.ToTable("Medications");

                            b1.WithOwner()
                                .HasForeignKey("MedicationId");
                        });

                    b.Navigation("Dose")
                        .IsRequired();
                });

            modelBuilder.Entity("MoodTracker.Server.Domain.Day", b =>
                {
                    b.Navigation("_medications");
                });
#pragma warning restore 612, 618
        }
    }
}
