@MoodTracker.Server_HostAddress = https://localhost:7013

GET {{MoodTracker.Server_HostAddress}}/api/Notes/GetNote/2025-11-03
Accept: application/json


###
GET {{MoodTracker.Server_HostAddress}}/api/Notes/GetMedication/7/4
Accept: application/json


###
DELETE {{MoodTracker.Server_HostAddress}}/api/Notes/DeleteMedication
Content-Type: application/json
{
  "noteId": 7,
  "medicationId": 5
}

###
GET {{MoodTracker.Server_HostAddress}}/api/MoodProgress/GetProgress/2025-11-08
Accept: application/json


GET {{MoodTracker.Server_HostAddress}}/api/MoodProgress/GetProgress/{date}

###

@date=2025-12-04
GET {{MoodTracker.Server_HostAddress}}/api/Wellbutrin/GetWellbutrinDay/{{date}}

###
@date=2026-01-04
GET {{MoodTracker.Server_HostAddress}}/api/Histogram/GetMoodRateHistogram/{{date}}

###
@date=2026-01-04
GET {{MoodTracker.Server_HostAddress}}/api/Histogram/GetMoodColorHistogram/{{date}}

###